version: "3.9"
services:
        grobid:
                image: lfoppiano/grobid:0.6.2
                environment:
                        - JAVA_OPTS="-Xmx4096m"
                ports:
                        - "8070:8070"
                        - "8071:8071"
                configs:
                        - source: grobid-service-config
                          target: /opt/grobid/grobid-service/config/config.yaml
        app:
                build: .
                ports:
                        - "5000:5000"
configs:
        grobid-service-config:
                file: ./config.yml
